# Generated by Django 5.0.6 on 2024-06-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('specialty', models.CharField(choices=[('اختصاصي', 'Specialist'), ('داعم', 'Supporter')], default='اختصاصي', max_length=255)),
                ('degree', models.CharField(choices=[('مدرس', 'Phd'), ('ماستر', 'Master')], default='مدرس', max_length=255)),
                ('time', models.CharField(choices=[('كلي', 'Fulltime'), ('جزئي', 'Part Time')], default='كلي', max_length=255)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_countable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='base.faculty')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
