# Generated by Django 5.0.6 on 2024-06-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0006_rename_ratio_faculty_local_staff_percentage_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": [
                    "faculty__name",
                    "-is_countable",
                    "-degree",
                    "-time",
                    "specialty",
                    "-is_staff",
                    "name",
                ],
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.AlterField(
            model_name="staff",
            name="degree",
            field=models.CharField(
                choices=[("مدرس", "Phd"), ("ماستر", "Master")],
                default="مدرس",
                help_text="الدرجة العلمية دكتور، مدرس",
                max_length=255,
                verbose_name="الدرجة العلمية",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="faculty",
            field=models.ForeignKey(
                help_text="الكلية",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="faculties.faculty",
                verbose_name="الكلية",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_countable",
            field=models.BooleanField(
                default=True,
                help_text="لن يتم احتسابه ضمن معادلات حساب الطاقة أو الملاك و غيرها",
                verbose_name="يحتسب",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_staff",
            field=models.BooleanField(
                default=False, help_text="ضمن ملاك الجامعة الوطنية", verbose_name="ملاك"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="الإسم"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="notes",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="ملاحظات"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="specialty",
            field=models.CharField(
                choices=[("اختصاصي", "Specialist"), ("داعم", "Supporter")],
                default="اختصاصي",
                help_text="التخصص اختصاصي، داعم",
                max_length=255,
                verbose_name="التخصص",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="time",
            field=models.CharField(
                choices=[("كلي", "Fulltime"), ("جزئي", "Part Time")],
                default="كلي",
                help_text="التفرغ جزئي ، كلي",
                max_length=255,
                verbose_name="التفرغ",
            ),
        ),
    ]
