# Generated by Django 5.0.6 on 2024-07-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staff_options_alter_staff_degree_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": [
                    "faculty__name",
                    "-is_countable",
                    "-degree",
                    "-time",
                    "specialty",
                    "-is_local",
                    "name",
                ],
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="is_staff",
            new_name="is_local",
        ),
    ]
