# Generated by Django 5.0.6 on 2024-07-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0003_remove_specialty_is_supporter_and_more"),
        ("staff", "0003_alter_staff_options_rename_is_staff_staff_is_local"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": [
                    "specialty",
                    "-is_countable",
                    "-degree",
                    "-time",
                    "-is_local",
                    "name",
                ],
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.RemoveField(
            model_name="staff",
            name="faculty",
        ),
        migrations.AlterField(
            model_name="staff",
            name="specialty",
            field=models.ForeignKey(
                help_text="الاختصاص ضمن الكلية الواحدة",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="specialties.specialty",
                verbose_name="الاختصاص",
            ),
        ),
    ]
