# Generated by Django 5.0.6 on 2024-07-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "specialties",
            "0004_alter_specialty_is_specialist_alter_specialty_name_and_more",
        ),
        ("staff", "0004_alter_staff_options_remove_staff_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="degree",
            field=models.CharField(
                choices=[("PHD", "Phd"), ("Master", "Master")],
                default="PHD",
                help_text="Degree e.g.: PHD or Master",
                max_length=255,
                verbose_name="Degree",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_countable",
            field=models.BooleanField(
                default=True,
                help_text="To be calculated in capacity or local functions",
                verbose_name="Is countable",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_local",
            field=models.BooleanField(
                default=False, help_text="Is local or foreign", verbose_name="Is local"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="notes",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Notes"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="specialty",
            field=models.ForeignKey(
                help_text="Specialty in one faculty",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="specialties.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="time",
            field=models.CharField(
                choices=[("Fulltime", "Fulltime"), ("Part time", "Part Time")],
                default="Fulltime",
                help_text="Time e.g.: Fulltime or part time",
                max_length=255,
                verbose_name="وقت",
            ),
        ),
    ]
