# Generated by Django 5.0.6 on 2024-07-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0005_alter_specialty_faculty_and_more"),
        ("staff", "0005_alter_staff_degree_alter_staff_is_countable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="degree",
            field=models.CharField(
                choices=[("مدرس", "phd"), ("ماستر", "master")],
                default="مدرس",
                help_text="degree e.g.: PHD or Master",
                max_length=255,
                verbose_name="degree",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_countable",
            field=models.BooleanField(
                default=True,
                help_text="to be calculated in capacity or local functions",
                verbose_name="is countable",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_local",
            field=models.BooleanField(
                default=False, help_text="is local or foreign", verbose_name="is local"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="notes",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="notes"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="specialty",
            field=models.ForeignKey(
                help_text="specialty in one faculty",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="specialties.specialty",
                verbose_name="specialty",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="time",
            field=models.CharField(
                choices=[("كلي", "fulltime"), ("جزئي", "parttime")],
                default="كلي",
                help_text="time e.g.: Fulltime or part time",
                max_length=255,
                verbose_name="time",
            ),
        ),
    ]
