# Generated by Django 5.0.6 on 2024-07-04 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculties", "0009_delete_facultysupporter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم التخصص الداعم",
                        max_length=255,
                        verbose_name="اسم التخصص الداعم",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        default=35,
                        help_text="نسبة التخصص الداعم",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "count must be more than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "count must be less than 100"
                            ),
                        ],
                        verbose_name="نسبة التخصص الداعم",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialties",
                        to="faculties.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Specialties",
                "ordering": ["faculty__name"],
            },
        ),
    ]
