# Generated by Django 5.0.6 on 2024-07-04 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="is_supporter",
            field=models.BooleanField(
                default=False, help_text="داعم؟", verbose_name="داعم؟"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(
                help_text="اسم التخصص", max_length=255, verbose_name="اسم التخصص"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="percentage",
            field=models.PositiveIntegerField(
                default=35,
                help_text="نسبة التخصص",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "count must be less than 100"
                    ),
                ],
                verbose_name="نسبة التخصص",
            ),
        ),
    ]
