# Generated by Django 5.0.6 on 2024-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0002_specialty_is_supporter_alter_specialty_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="is_supporter",
        ),
        migrations.AddField(
            model_name="specialty",
            name="is_specialist",
            field=models.BooleanField(
                default=False, help_text="اختصاصي؟", verbose_name="اختصاصي؟"
            ),
        ),
    ]
