# Generated by Django 5.0.6 on 2024-07-06 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0003_remove_specialty_is_supporter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="is_specialist",
            field=models.BooleanField(
                default=False, help_text="Is specialist", verbose_name="Is specialist"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(
                help_text="The name of specialty", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="percentage",
            field=models.PositiveIntegerField(
                default=65,
                help_text="Percentage of the specialty",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "count must be less than 100"
                    ),
                ],
                verbose_name="Percentage",
            ),
        ),
    ]
