# Generated by Django 5.0.6 on 2024-07-10 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0012_alter_faculty_count_of_graduates_and_more"),
        (
            "specialties",
            "0004_alter_specialty_is_specialist_alter_specialty_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specialties",
                to="faculties.faculty",
                verbose_name="faculty",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="is_specialist",
            field=models.BooleanField(
                default=False, help_text="is specialist", verbose_name="is specialist"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(
                help_text="the name of specialty", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="percentage",
            field=models.PositiveIntegerField(
                default=65,
                help_text="percentage of the specialty",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "count must be less than 100"
                    ),
                ],
                verbose_name="percentage",
            ),
        ),
    ]
