# Generated by Django 5.0.6 on 2024-06-05 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('count_of_scholarship_students', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0')])),
                ('count_of_graduates', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0')])),
                ('count_of_students', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0')])),
                ('count_of_new_students', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0')])),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
