# Generated by Django 5.0.6 on 2024-06-05 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ratio',
            field=models.PositiveBigIntegerField(default=35, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0')]),
        ),
    ]
