# Generated by Django 5.0.6 on 2024-06-05 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_faculty_ratio_count_faculty_ratio_staff_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ratio_specialist_support',
            field=models.PositiveBigIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0, 'count must be more than 0'), django.core.validators.MaxValueValidator(100, 'count must be less than 100')]),
        ),
    ]
