# Generated by Django 5.0.6 on 2024-06-25 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0004_faculty_ratio_specialist_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="count_of_new_students",
        ),
        migrations.AlterField(
            model_name="faculty",
            name="count_of_graduates",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="عدد الخريجين",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد الخريجين",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="count_of_scholarship_students",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="عدد طلاب المنح",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد طلاب المنح",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="count_of_students",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="عدد الطلاب دون الخريجين والمنح",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد الطلاب",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="الإسم"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="ratio",
            field=models.PositiveBigIntegerField(
                default=50,
                help_text="نسبة الملاك الذي يجب تحقيقها",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "count must be less than 100"
                    ),
                ],
                verbose_name="نسبة الملاك الوزارة",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="ratio_count",
            field=models.PositiveBigIntegerField(
                default=35,
                help_text="عدد الطلاب المسموح به لكل مدرس",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد الطلاب لكل مدرس",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="ratio_specialist_support",
            field=models.PositiveBigIntegerField(
                default=30,
                help_text="نسبة الداعم الى الاختصاصي",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "count must be less than 100"
                    ),
                ],
                verbose_name="نسبة الداعم",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="ratio_staff_count",
            field=models.PositiveBigIntegerField(
                default=20,
                help_text="عدد الطلاب حسب الاعتمادية (الملاك)",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد الطلاب (الاعتمادية)",
            ),
        ),
    ]
