# Generated by Django 5.0.6 on 2024-06-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0005_remove_faculty_count_of_new_students_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="ratio",
            new_name="local_staff_percentage",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="ratio_staff_count",
            new_name="student_to_local_teacher_count",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="ratio_count",
            new_name="student_to_teacher_count",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="ratio_specialist_support",
            new_name="supporters_percentage",
        ),
    ]
