# Generated by Django 5.0.6 on 2024-07-01 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0006_rename_ratio_faculty_local_staff_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="count_of_students",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="عدد الطلاب متضمن الخريجين والمنح",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="عدد الطلاب",
            ),
        ),
    ]
