# Generated by Django 5.0.6 on 2024-07-03 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0007_alter_faculty_count_of_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultySupporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم التخصص الداعم",
                        max_length=255,
                        verbose_name="اسم التخصص الداعم",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        help_text="نسبة التخصص الداعم",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "count must be more than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "count must be less than 100"
                            ),
                        ],
                        verbose_name="نسبة التخصص الداعم",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supporters",
                        to="faculties.faculty",
                    ),
                ),
            ],
        ),
    ]
