# Generated by Django 5.0.6 on 2024-07-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0008_facultysupporter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacultySupporter",
        ),
    ]
