# Generated by Django 5.0.6 on 2024-07-10 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0012_alter_faculty_count_of_graduates_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="local_staff_percentage",
        ),
        migrations.AddField(
            model_name="faculty",
            name="count_of_new_students",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="count of desired students",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "count must be more than 0"
                    )
                ],
                verbose_name="new students count",
            ),
        ),
    ]
